package com.example.bmi;

import java.io.Serializable;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/*
 * Author: Adrianus Jonathan Engelbracht
 * Created: 06.07.2023
 * Matrikelnummer: 1151826
 */

@Entity
public class Person implements Serializable {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	private String name;
	private float weight;
	private float height;
	private float bmi;
	
	
	// no args constructor
	public Person() {		
	}
		
	// id is generated by Database 
//	public Long getId() {
//		return id;
//	}

//	public void setId(Long id) {
//		this.id = id;
//	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public float getWeight() {
		return weight;
	}
	public void setWeight(float weight) {
		this.weight = weight;
	}
	public float getHeight() {
		return height;
	}
	public void setHeight(float height) {
		this.height = height;
	}
	public float getBmi() {
		return bmi;
	}
	public void setBmi(float bmi) {
		this.bmi = bmi;
	}
	
	public float calculateBMI() {
		float result = 0;
		if(weight > 0 && height > 0) {
			result = weight / (height * height);
		}
		return result;
	}
	
	
	

}
